version: '2'

services:
  openvpn:
    container_name: openvpn
    image: kylemanna/openvpn
    ports:
      - "1194:1194/udp"
    restart: unless-stopped
    volumes:
      - ./data:/etc/openvpn
    cap_add:
      - NET_ADMIN
